package com.cmdfootball.service;

import com.cmdfootball.model.Player;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.PdfPTable;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.util.List;

@Service
public class PdfReportService {

    public byte[] createPdfReport(List<Player> players) {
        try {
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            Document document = new Document();
            PdfWriter.getInstance(document, out);
            document.open();

            // Coach summary
            document.add(new Paragraph("🏟️ Coach Summary"));
            document.add(new Paragraph("CMD Football is live and tracking player progress. This report reflects current effort scores, badge achievements, and team composition.\n\n"));

            // Player registry table
            PdfPTable table = new PdfPTable(6); // ID, Name, Position, Age, Effort, Badges
            table.addCell("ID");
            table.addCell("Name");
            table.addCell("Position");
            table.addCell("Age");
            table.addCell("Effort Score");
            table.addCell("Badges");

            for (Player p : players) {
                table.addCell(String.valueOf(p.getId()));
                table.addCell(p.getName());
                table.addCell(p.getPosition());
                table.addCell(String.valueOf(p.getAge()));
                table.addCell(String.format("%.2f", p.getEffortScore()));
                table.addCell(String.join(" | ", p.getBadges()));
            }

            document.add(table);

            // Footer
            document.add(new Paragraph("\n📄 Report generated by CMD Football — Empowering Coaches Worldwide"));

            document.close();
            return out.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate PDF", e);
        }
    }
}